language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
env:
  - MAIN_DIR=sinon
install:
  - pip install -U pip
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls
script:
  - python -m doctest example/doctest_example.py
  - cd $MAIN_DIR
  - python -m doctest lib/util/CollectionHandler.py
  - cd test
  - python -m unittest TestSinonBase TestSinonSpy TestSinonStub TestSinonSandbox TestSinonMock TestSinonAssertion TestSinonMatcher
  - cd ../../example/restful_flask_example_with_sinon/
  - pip install -r requirement.txt
  - python test.py
after_success:
  - coverage run --source=../lib/ -m unittest TestSinonBase TestSinonSpy TestSinonStub TestSinonSandbox TestSinonMock TestSinonAssertion TestSinonMatcher
  - coverage report -m
  - coveralls
